---
swagger: "2.0"
info:
  description: "This is the API that will run on the cplex server. Scheduling agents\
    \ can call this API.  You can find \nout more about Swagger at \n[http://swagger.io](http://swagger.io)\
    \ or on \n[irc.freenode.net, #swagger](http://swagger.io/irc/).\n"
  version: "1.0.0"
  title: "Cplex Server"
  termsOfService: "http://swagger.io/terms/"
  contact:
    email: "apiteam@swagger.io"
  license:
    name: "Apache 2.0"
    url: "http://www.apache.org/licenses/LICENSE-2.0.html"
host: "virtserver.swaggerhub.com"
basePath: "/cpsc490/cplex_server/1.0.0"
schemes:
- "https"
- "http"
paths:
  /optimize:
    post:
      summary: "Submit json for cplex to optimize job"
      operationId: "submit_job"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - in: "body"
        name: "body"
        description: "Parameters for cplex to optimize with"
        required: true
        schema:
          $ref: "#/definitions/Parameters"
      responses:
        200:
          description: "successful operation"
          schema:
            type: "object"
            additionalProperties:
              type: "integer"
              format: "int32"
        405:
          description: "Invalid input"
      x-swagger-router-controller: "cplex_server.controllers.default_controller"
  /status/{jobId}:
    get:
      summary: "Finds job status for id"
      operationId: "find_status_by_job_id"
      produces:
      - "application/json"
      parameters:
      - name: "jobId"
        in: "path"
        description: "ID of job to return status for"
        required: true
        type: "integer"
        format: "int64"
      responses:
        200:
          description: "successful operation"
          schema:
            $ref: "#/definitions/JobStatus"
        400:
          description: "Invalid status value"
      x-swagger-router-controller: "cplex_server.controllers.default_controller"
  /bijobmatrix/{jobId}:
    get:
      summary: "Returns BIJob matrix for job with id"
      operationId: "get_bi_job_matrix"
      produces:
      - "application/json"
      parameters:
      - name: "jobId"
        in: "path"
        description: "ID of job to return status for"
        required: true
        type: "integer"
        format: "int64"
      responses:
        200:
          description: "successful operation"
          schema:
            $ref: "#/definitions/BIJobMatrix"
        400:
          description: "Invalid status value"
      x-swagger-router-controller: "cplex_server.controllers.default_controller"
  /imatrix/{jobId}:
    get:
      summary: "Returns I matrix for job with id"
      operationId: "get_i_matrix"
      produces:
      - "application/json"
      parameters:
      - name: "jobId"
        in: "path"
        description: "ID of job to return status for"
        required: true
        type: "integer"
        format: "int64"
      responses:
        200:
          description: "successful operation"
          schema:
            $ref: "#/definitions/IMatrix"
        400:
          description: "Invalid"
      x-swagger-router-controller: "cplex_server.controllers.default_controller"
definitions:
  Parameters:
    type: "object"
    required:
    - "A"
    - "C"
    - "destNodes"
    - "jobs"
    - "numConstraints"
    - "sourceNodes"
    properties:
      sourceNodes:
        type: "array"
        example:
        - "m1"
        - "m2"
        items:
          type: "string"
      destNodes:
        type: "array"
        example:
        - "n1"
        - "n2"
        items:
          type: "string"
      jobs:
        type: "array"
        example:
        - "j1"
        - "j2"
        items:
          type: "string"
      numConstraints:
        type: "integer"
        example: 5
      A:
        type: "array"
        example:
        - - 1
          - 0
          - 0
          - 0
        - - 0
          - 1
          - 0
          - 0
        - - 0
          - 0
          - 1
          - 0
        - - 0
          - 0
          - 0
          - 1
        - - 0
          - 0
          - 1
          - 1
        items:
          type: "array"
          items:
            type: "integer"
      C:
        type: "array"
        example:
        - 4
        - 5
        - 2
        - 6
        - 7
        items:
          type: "integer"
    example:
      destNodes:
      - "n1"
      - "n2"
      A:
      - - 1
        - 0
        - 0
        - 0
      - - 0
        - 1
        - 0
        - 0
      - - 0
        - 0
        - 1
        - 0
      - - 0
        - 0
        - 0
        - 1
      - - 0
        - 0
        - 1
        - 1
      C:
      - 4
      - 5
      - 2
      - 6
      - 7
      sourceNodes:
      - "m1"
      - "m2"
      jobs:
      - "j1"
      - "j2"
      numConstraints: 5
  BIJobMatrix:
    type: "object"
    required:
    - "BIJobMatrix"
    - "jobId"
    properties:
      jobId:
        type: "integer"
        format: "int32"
      BIJobMatrix:
        type: "array"
        example:
        - 7
        - 8
        items:
          type: "integer"
    example:
      BIJobMatrix:
      - 7
      - 8
      jobId: 0
  IMatrix:
    type: "object"
    required:
    - "iMatrix"
    - "jobId"
    properties:
      jobId:
        type: "integer"
        format: "int32"
      iMatrix:
        type: "array"
        example:
        - - 1
          - 0
        - - 0
          - 1
        - - 0
          - 0
        - - 0
          - 0
        items:
          type: "array"
          items:
            type: "integer"
    example:
      jobId: 0
      iMatrix:
      - - 1
        - 0
      - - 0
        - 1
      - - 0
        - 0
      - - 0
        - 0
  JobStatus:
    type: "object"
    required:
    - "jobId"
    - "status"
    properties:
      jobId:
        type: "integer"
        format: "int32"
      status:
        type: "string"
        enum:
        - "processing"
        - "done"
        - "not found"
    example:
      jobId: 0
      status: "processing"
externalDocs:
  description: "Find out more about Swagger"
  url: "http://swagger.io"
