# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from cplex_server.models.base_model_ import Model
from cplex_server import util


class IMatrix(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    def __init__(self, job_id: int=None, i_matrix: List[List[int]]=None):  # noqa: E501
        """IMatrix - a model defined in Swagger

        :param job_id: The job_id of this IMatrix.  # noqa: E501
        :type job_id: int
        :param i_matrix: The i_matrix of this IMatrix.  # noqa: E501
        :type i_matrix: List[List[int]]
        """
        self.swagger_types = {
            'job_id': int,
            'i_matrix': List[List[int]]
        }

        self.attribute_map = {
            'job_id': 'jobId',
            'i_matrix': 'iMatrix'
        }

        self._job_id = job_id
        self._i_matrix = i_matrix

    @classmethod
    def from_dict(cls, dikt) -> 'IMatrix':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The IMatrix of this IMatrix.  # noqa: E501
        :rtype: IMatrix
        """
        return util.deserialize_model(dikt, cls)

    @property
    def job_id(self) -> int:
        """Gets the job_id of this IMatrix.


        :return: The job_id of this IMatrix.
        :rtype: int
        """
        return self._job_id

    @job_id.setter
    def job_id(self, job_id: int):
        """Sets the job_id of this IMatrix.


        :param job_id: The job_id of this IMatrix.
        :type job_id: int
        """
        if job_id is None:
            raise ValueError("Invalid value for `job_id`, must not be `None`")  # noqa: E501

        self._job_id = job_id

    @property
    def i_matrix(self) -> List[List[int]]:
        """Gets the i_matrix of this IMatrix.


        :return: The i_matrix of this IMatrix.
        :rtype: List[List[int]]
        """
        return self._i_matrix

    @i_matrix.setter
    def i_matrix(self, i_matrix: List[List[int]]):
        """Sets the i_matrix of this IMatrix.


        :param i_matrix: The i_matrix of this IMatrix.
        :type i_matrix: List[List[int]]
        """
        if i_matrix is None:
            raise ValueError("Invalid value for `i_matrix`, must not be `None`")  # noqa: E501

        self._i_matrix = i_matrix
